name: becertus_proyecto
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  get: ^4.6.6
  rxdart: ^0.27.7
  cupertino_icons: ^1.0.2
  badges: ^3.1.2
  flutter_speed_dial: ^7.0.0
  intl: ^0.18.1
  blur: ^3.1.0
  auto_size_text: ^3.0.0
  firebase_core: ^2.20.0
  ffi: ^2.1.0
  firebase_database: ^10.3.2
  cloud_firestore: ^4.12.1
  provider: ^6.0.5
  syncfusion_flutter_calendar: ^23.1.44
  syncfusion_localizations: ^23.1.44
  shared_preferences: ^2.2.2
  firebase_messaging: ^14.7.3
  firebase_auth: ^4.12.1
  cached_network_image: ^3.3.0
  path_provider: ^2.1.1
  glassmorphism: ^3.0.0
  flutter_lints: ^2.0.0
  syncfusion_flutter_charts: ^23.1.42
  syncfusion_flutter_gauges: ^23.1.44
  table_calendar: ^3.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_svg: ^2.0.7
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/start/
     - assets/images/
     - assets/elements/
     - assets/images/iconos/

  
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  fonts:
    - family: Mitr
      fonts:
        - asset: assets/fonts/Mitr-Bold.ttf
          weight: 700
        - asset: assets/fonts/Mitr-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Mitr-Light.ttf
          weight: 300
        - asset: assets/fonts/Mitr-Medium.ttf
          weight: 500
        - asset: assets/fonts/Mitr-Regular.ttf
          weight: 400
        - asset: assets/fonts/Mitr-SemiBold.ttf
          weight: 600
    - family: Arimo
      fonts:
        - asset: assets/fonts/Arimo-VariableFont_wght.ttf
          weight: 200
        - asset: assets/fonts/Arimo-Bold.ttf
          weight: 600
        - asset: assets/fonts/Arimo-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Arimo-Medium.ttf
          weight: 400
        - asset: assets/fonts/Arimo-Regular.ttf
          weight: 300

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
